### ISSUE TITLE
HOME Button on remote

### ISSUE THREAD

**Issue by DavidMaarek** [securechicken/homebridge-freebox-player-delta#3]
From what I have read, it is impossible to create a remote control with custom buttons, specifying that we want precisely this or that button? Like the "HOME" button, I see that it is created in the index.js line 137, but in the remote there is only "Play / Pause", "BACK" and "INFORMATIONS".
If you confirm to me that it is not possible to make this "HOME" button appear, would it be possible to replace the "INFORMATION" button, which I find is used very little, by this "HOME" button ?
If not, could I fork this project, and publish it with this change for people interested in it like me? Or is it possible to manage this information in config ?
Thank you very much.

**Comment by securechicken** [comment]
Closed due to invalid request format (the issue do not use an issue template and do not provide requested information) + topic out of scope (Apple Remote related question, HomeBridge API related question).
